# Simple package

name: simple-package 
parent: default

matches:
  - trigger: ":vimeohtml"
    replace: |
              <div class="media-box-usq">
              <div class="media-box-header">
              <div class="media-box-header__title left col-lg-12"><span class="text-15 bold">WATCH<br/>   <<<VIDEOHEAD>>>   </span>
              <p>  <<<VIDEODESCRIPTION>>>  </p>
              <div class="media-box-center"><iframe src="   <<<VIDEOLINK>>>   " width="640" height="320" allowfullscreen="allowfullscreen" webkitallowfullscreen="webkitallowfullscreen" mozallowfullscreen="mozallowfullscreen"></iframe></div>
              <span><span>Video not loading? <a href="   <<<VIDEOLINK>>>   ">View on Vimeo</a>.<br /></span><a href="   <<<VIDEOTRANSCRIPT>>>   "Download the transcript for this video</a>.</span></div>
              </div>
              </div>